[versions]
purefunVersion = "5.2-SNAPSHOT"
purejsonVersion = "1.2-SNAPSHOT"
purecfgVersion = "1.2-SNAPSHOT"
puredbcVersion = "1.2-SNAPSHOT"
purecheckVersion = "1.2-SNAPSHOT"
zeromockVersion = "1.3-SNAPSHOT"
hikaricpVersion = "7.0.2"
h2Version = "2.4.240"
logbackVersion = "1.5.32"
mockitoVersion = "5.21.0"
junitVersion = "6.0.3"
assertjVersion = "3.27.7"
versionsVersion = "0.53.0"
downloadVersion = "5.7.0"
graalvmNativeImageVersion = "0.11.4"
errorproneVersion = "2.47.0"
errorpronePluginVersion = "5.0.0"
nullawayVersion = "0.13.1"

[libraries]
purefunMonad = { group = "com.github.tonivade", name = "purefun-monad", version.ref = "purefunVersion" }
purefunEffect = { group = "com.github.tonivade", name = "purefun-effect", version.ref = "purefunVersion" }
purefunTransformer = { group = "com.github.tonivade", name = "purefun-transformer", version.ref = "purefunVersion" }
purefunInstances = { group = "com.github.tonivade", name = "purefun-instances", version.ref = "purefunVersion" }
zeromockServer = { group = "com.github.tonivade", name = "zeromock-server", version.ref = "zeromockVersion" }
purecfg = { group = "com.github.tonivade", name = "purecfg", version.ref = "purecfgVersion" }
puredbc = { group = "com.github.tonivade", name = "puredbc", version.ref = "puredbcVersion" }
purejson = { group = "com.github.tonivade", name = "purejson", version.ref = "purejsonVersion" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricpVersion" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2Version" }
logbackClassic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" }
zeromockJunit5 = { group = "com.github.tonivade", name = "zeromock-junit5", version.ref = "zeromockVersion" }
zeromockClient = { group = "com.github.tonivade", name = "zeromock-client", version.ref = "zeromockVersion" }
purecheck = { group = "com.github.tonivade", name = "purecheck", version.ref = "purecheckVersion" }
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitVersion" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter-engine" }
junitLauncher = { module = "org.junit.platform:junit-platform-launcher" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoVersion" }
mockitoJunitJupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoVersion" }
assertjCore = { group = "org.assertj", name = "assertj-core", version.ref = "assertjVersion" } 
nullaway = { group = "com.uber.nullaway", name = "nullaway", version.ref = "nullawayVersion" }
errorprone = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorproneVersion" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsVersion" }
graalvmNativeImage = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNativeImageVersion" }
download = {  id = "de.undercouch.download", version.ref = "downloadVersion" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePluginVersion"}